# 3 node network: TTP (Bank), Client, Merchant

############### Component settings ###############
quantum_device_settings: &qdevice_cfg
  num_qubits: 20

  # coherence times (ns)
  T1: 0
  T2: 0

  # gate execution times (ns)
  init_time: 0
  single_qubit_gate_time: 0
  two_qubit_gate_time: 0
  measure_time: 0

  # noise model (probability)
  single_qubit_gate_depolar_prob: 0.
  two_qubit_gate_depolar_prob: 0.


quantum_link_settings: &qlink_cfg
  # Fidelity of generated EPR pairs
  fidelity: 1
  # Chance to succeed generating an EPR pair per entanglement attempt cycle (probability)
  prob_success: 1
  # Duration of an entanglement attempt cycle (ns)
  t_cycle: 1e5


classical_link_settings: &clink_cfg
  # Duration for a classical message to transmit to another node (ns)
  delay: 0


############### Network ###############
stacks:
  - name: TTP
    qdevice_typ: generic
    qdevice_cfg:
      <<: *qdevice_cfg

  - name: Client
    qdevice_typ: generic
    qdevice_cfg:
      <<: *qdevice_cfg

  - name: Merchant
    qdevice_typ: generic
    qdevice_cfg:
      <<: *qdevice_cfg


links:
  - stack1: TTP
    stack2: Client
    typ: depolarise
    cfg:
      <<: *qlink_cfg

  - stack1: Client
    stack2: Merchant
    typ: depolarise
    cfg:
      <<: *qlink_cfg

  - stack1: Merchant
    stack2: TTP
    typ: depolarise
    cfg:
      <<: *qlink_cfg


clinks:
  - stack1: TTP
    stack2: Client
    typ: default
    cfg:
      <<: *clink_cfg

  - stack1: Client
    stack2: Merchant
    typ: default
    cfg:
      <<: *clink_cfg

  - stack1: Merchant
    stack2: TTP
    typ: default
    cfg:
      <<: *clink_cfg